// Generated by gencpp from file crtk_msgs/trigger_operating_state.msg
// DO NOT EDIT!


#ifndef CRTK_MSGS_MESSAGE_TRIGGER_OPERATING_STATE_H
#define CRTK_MSGS_MESSAGE_TRIGGER_OPERATING_STATE_H

#include <ros/service_traits.h>


#include <crtk_msgs/trigger_operating_stateRequest.h>
#include <crtk_msgs/trigger_operating_stateResponse.h>


namespace crtk_msgs
{

struct trigger_operating_state
{

typedef trigger_operating_stateRequest Request;
typedef trigger_operating_stateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct trigger_operating_state
} // namespace crtk_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::crtk_msgs::trigger_operating_state > {
  static const char* value()
  {
    return "d941a2d049e2c9ac5773fc4a3a8a892d";
  }

  static const char* value(const ::crtk_msgs::trigger_operating_state&) { return value(); }
};

template<>
struct DataType< ::crtk_msgs::trigger_operating_state > {
  static const char* value()
  {
    return "crtk_msgs/trigger_operating_state";
  }

  static const char* value(const ::crtk_msgs::trigger_operating_state&) { return value(); }
};


// service_traits::MD5Sum< ::crtk_msgs::trigger_operating_stateRequest> should match
// service_traits::MD5Sum< ::crtk_msgs::trigger_operating_state >
template<>
struct MD5Sum< ::crtk_msgs::trigger_operating_stateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::crtk_msgs::trigger_operating_state >::value();
  }
  static const char* value(const ::crtk_msgs::trigger_operating_stateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::crtk_msgs::trigger_operating_stateRequest> should match
// service_traits::DataType< ::crtk_msgs::trigger_operating_state >
template<>
struct DataType< ::crtk_msgs::trigger_operating_stateRequest>
{
  static const char* value()
  {
    return DataType< ::crtk_msgs::trigger_operating_state >::value();
  }
  static const char* value(const ::crtk_msgs::trigger_operating_stateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::crtk_msgs::trigger_operating_stateResponse> should match
// service_traits::MD5Sum< ::crtk_msgs::trigger_operating_state >
template<>
struct MD5Sum< ::crtk_msgs::trigger_operating_stateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::crtk_msgs::trigger_operating_state >::value();
  }
  static const char* value(const ::crtk_msgs::trigger_operating_stateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::crtk_msgs::trigger_operating_stateResponse> should match
// service_traits::DataType< ::crtk_msgs::trigger_operating_state >
template<>
struct DataType< ::crtk_msgs::trigger_operating_stateResponse>
{
  static const char* value()
  {
    return DataType< ::crtk_msgs::trigger_operating_state >::value();
  }
  static const char* value(const ::crtk_msgs::trigger_operating_stateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CRTK_MSGS_MESSAGE_TRIGGER_OPERATING_STATE_H
