// Generated by gencpp from file cisst_msgs/QueryForwardKinematics.msg
// DO NOT EDIT!


#ifndef CISST_MSGS_MESSAGE_QUERYFORWARDKINEMATICS_H
#define CISST_MSGS_MESSAGE_QUERYFORWARDKINEMATICS_H

#include <ros/service_traits.h>


#include <cisst_msgs/QueryForwardKinematicsRequest.h>
#include <cisst_msgs/QueryForwardKinematicsResponse.h>


namespace cisst_msgs
{

struct QueryForwardKinematics
{

typedef QueryForwardKinematicsRequest Request;
typedef QueryForwardKinematicsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct QueryForwardKinematics
} // namespace cisst_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cisst_msgs::QueryForwardKinematics > {
  static const char* value()
  {
    return "777a4ccce3ab2f993d2444440e63f814";
  }

  static const char* value(const ::cisst_msgs::QueryForwardKinematics&) { return value(); }
};

template<>
struct DataType< ::cisst_msgs::QueryForwardKinematics > {
  static const char* value()
  {
    return "cisst_msgs/QueryForwardKinematics";
  }

  static const char* value(const ::cisst_msgs::QueryForwardKinematics&) { return value(); }
};


// service_traits::MD5Sum< ::cisst_msgs::QueryForwardKinematicsRequest> should match
// service_traits::MD5Sum< ::cisst_msgs::QueryForwardKinematics >
template<>
struct MD5Sum< ::cisst_msgs::QueryForwardKinematicsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cisst_msgs::QueryForwardKinematics >::value();
  }
  static const char* value(const ::cisst_msgs::QueryForwardKinematicsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cisst_msgs::QueryForwardKinematicsRequest> should match
// service_traits::DataType< ::cisst_msgs::QueryForwardKinematics >
template<>
struct DataType< ::cisst_msgs::QueryForwardKinematicsRequest>
{
  static const char* value()
  {
    return DataType< ::cisst_msgs::QueryForwardKinematics >::value();
  }
  static const char* value(const ::cisst_msgs::QueryForwardKinematicsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cisst_msgs::QueryForwardKinematicsResponse> should match
// service_traits::MD5Sum< ::cisst_msgs::QueryForwardKinematics >
template<>
struct MD5Sum< ::cisst_msgs::QueryForwardKinematicsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cisst_msgs::QueryForwardKinematics >::value();
  }
  static const char* value(const ::cisst_msgs::QueryForwardKinematicsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cisst_msgs::QueryForwardKinematicsResponse> should match
// service_traits::DataType< ::cisst_msgs::QueryForwardKinematics >
template<>
struct DataType< ::cisst_msgs::QueryForwardKinematicsResponse>
{
  static const char* value()
  {
    return DataType< ::cisst_msgs::QueryForwardKinematics >::value();
  }
  static const char* value(const ::cisst_msgs::QueryForwardKinematicsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CISST_MSGS_MESSAGE_QUERYFORWARDKINEMATICS_H
