// Generated by gencpp from file cisst_msgs/QueryForwardKinematicsResponse.msg
// DO NOT EDIT!


#ifndef CISST_MSGS_MESSAGE_QUERYFORWARDKINEMATICSRESPONSE_H
#define CISST_MSGS_MESSAGE_QUERYFORWARDKINEMATICSRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PoseStamped.h>

namespace cisst_msgs
{
template <class ContainerAllocator>
struct QueryForwardKinematicsResponse_
{
  typedef QueryForwardKinematicsResponse_<ContainerAllocator> Type;

  QueryForwardKinematicsResponse_()
    : cp()  {
    }
  QueryForwardKinematicsResponse_(const ContainerAllocator& _alloc)
    : cp(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _cp_type;
  _cp_type cp;





  typedef boost::shared_ptr< ::cisst_msgs::QueryForwardKinematicsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cisst_msgs::QueryForwardKinematicsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct QueryForwardKinematicsResponse_

typedef ::cisst_msgs::QueryForwardKinematicsResponse_<std::allocator<void> > QueryForwardKinematicsResponse;

typedef boost::shared_ptr< ::cisst_msgs::QueryForwardKinematicsResponse > QueryForwardKinematicsResponsePtr;
typedef boost::shared_ptr< ::cisst_msgs::QueryForwardKinematicsResponse const> QueryForwardKinematicsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cisst_msgs::QueryForwardKinematicsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cisst_msgs::QueryForwardKinematicsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cisst_msgs::QueryForwardKinematicsResponse_<ContainerAllocator1> & lhs, const ::cisst_msgs::QueryForwardKinematicsResponse_<ContainerAllocator2> & rhs)
{
  return lhs.cp == rhs.cp;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cisst_msgs::QueryForwardKinematicsResponse_<ContainerAllocator1> & lhs, const ::cisst_msgs::QueryForwardKinematicsResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cisst_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::cisst_msgs::QueryForwardKinematicsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cisst_msgs::QueryForwardKinematicsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cisst_msgs::QueryForwardKinematicsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cisst_msgs::QueryForwardKinematicsResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cisst_msgs::QueryForwardKinematicsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cisst_msgs::QueryForwardKinematicsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cisst_msgs::QueryForwardKinematicsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dcf42bd3051d9ea5a90899ecedcae4af";
  }

  static const char* value(const ::cisst_msgs::QueryForwardKinematicsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdcf42bd3051d9ea5ULL;
  static const uint64_t static_value2 = 0xa90899ecedcae4afULL;
};

template<class ContainerAllocator>
struct DataType< ::cisst_msgs::QueryForwardKinematicsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cisst_msgs/QueryForwardKinematicsResponse";
  }

  static const char* value(const ::cisst_msgs::QueryForwardKinematicsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cisst_msgs::QueryForwardKinematicsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/PoseStamped cp\n"
"\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::cisst_msgs::QueryForwardKinematicsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cisst_msgs::QueryForwardKinematicsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.cp);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct QueryForwardKinematicsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cisst_msgs::QueryForwardKinematicsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cisst_msgs::QueryForwardKinematicsResponse_<ContainerAllocator>& v)
  {
    s << indent << "cp: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.cp);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CISST_MSGS_MESSAGE_QUERYFORWARDKINEMATICSRESPONSE_H
