# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from cisst_msgs/mtsIntervalStatistics.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class mtsIntervalStatistics(genpy.Message):
  _md5sum = "fc177c4951f85470a8a9c80c56822cfb"
  _type = "cisst_msgs/mtsIntervalStatistics"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """Header header

# average period 
float64 PeriodAvg
# deviation on periodicity
float64 PeriodStdDev
# min and max time between
float64 PeriodMin
float64 PeriodMax
# same 4 values for compute time
float64 ComputeTimeAvg
float64 ComputeTimeStdDev
float64 ComputeTimeMin
float64 ComputeTimeMax
# number of samples used to compute these status
int64 NumberOfSamples
# number of overruns base on previous interval average
int64 NumberOfOverruns
# time window covered by these stats
float64 StatisticsInterval

# user data
int64 UserData

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id
"""
  __slots__ = ['header','PeriodAvg','PeriodStdDev','PeriodMin','PeriodMax','ComputeTimeAvg','ComputeTimeStdDev','ComputeTimeMin','ComputeTimeMax','NumberOfSamples','NumberOfOverruns','StatisticsInterval','UserData']
  _slot_types = ['std_msgs/Header','float64','float64','float64','float64','float64','float64','float64','float64','int64','int64','float64','int64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,PeriodAvg,PeriodStdDev,PeriodMin,PeriodMax,ComputeTimeAvg,ComputeTimeStdDev,ComputeTimeMin,ComputeTimeMax,NumberOfSamples,NumberOfOverruns,StatisticsInterval,UserData

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(mtsIntervalStatistics, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.PeriodAvg is None:
        self.PeriodAvg = 0.
      if self.PeriodStdDev is None:
        self.PeriodStdDev = 0.
      if self.PeriodMin is None:
        self.PeriodMin = 0.
      if self.PeriodMax is None:
        self.PeriodMax = 0.
      if self.ComputeTimeAvg is None:
        self.ComputeTimeAvg = 0.
      if self.ComputeTimeStdDev is None:
        self.ComputeTimeStdDev = 0.
      if self.ComputeTimeMin is None:
        self.ComputeTimeMin = 0.
      if self.ComputeTimeMax is None:
        self.ComputeTimeMax = 0.
      if self.NumberOfSamples is None:
        self.NumberOfSamples = 0
      if self.NumberOfOverruns is None:
        self.NumberOfOverruns = 0
      if self.StatisticsInterval is None:
        self.StatisticsInterval = 0.
      if self.UserData is None:
        self.UserData = 0
    else:
      self.header = std_msgs.msg.Header()
      self.PeriodAvg = 0.
      self.PeriodStdDev = 0.
      self.PeriodMin = 0.
      self.PeriodMax = 0.
      self.ComputeTimeAvg = 0.
      self.ComputeTimeStdDev = 0.
      self.ComputeTimeMin = 0.
      self.ComputeTimeMax = 0.
      self.NumberOfSamples = 0
      self.NumberOfOverruns = 0
      self.StatisticsInterval = 0.
      self.UserData = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_8d2qdq().pack(_x.PeriodAvg, _x.PeriodStdDev, _x.PeriodMin, _x.PeriodMax, _x.ComputeTimeAvg, _x.ComputeTimeStdDev, _x.ComputeTimeMin, _x.ComputeTimeMax, _x.NumberOfSamples, _x.NumberOfOverruns, _x.StatisticsInterval, _x.UserData))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 96
      (_x.PeriodAvg, _x.PeriodStdDev, _x.PeriodMin, _x.PeriodMax, _x.ComputeTimeAvg, _x.ComputeTimeStdDev, _x.ComputeTimeMin, _x.ComputeTimeMax, _x.NumberOfSamples, _x.NumberOfOverruns, _x.StatisticsInterval, _x.UserData,) = _get_struct_8d2qdq().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_8d2qdq().pack(_x.PeriodAvg, _x.PeriodStdDev, _x.PeriodMin, _x.PeriodMax, _x.ComputeTimeAvg, _x.ComputeTimeStdDev, _x.ComputeTimeMin, _x.ComputeTimeMax, _x.NumberOfSamples, _x.NumberOfOverruns, _x.StatisticsInterval, _x.UserData))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 96
      (_x.PeriodAvg, _x.PeriodStdDev, _x.PeriodMin, _x.PeriodMax, _x.ComputeTimeAvg, _x.ComputeTimeStdDev, _x.ComputeTimeMin, _x.ComputeTimeMax, _x.NumberOfSamples, _x.NumberOfOverruns, _x.StatisticsInterval, _x.UserData,) = _get_struct_8d2qdq().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_8d2qdq = None
def _get_struct_8d2qdq():
    global _struct_8d2qdq
    if _struct_8d2qdq is None:
        _struct_8d2qdq = struct.Struct("<8d2qdq")
    return _struct_8d2qdq
