(cl:defpackage crtk_msgs-srv
  (:use )
  (:export
   "TRIGGER_OPERATING_STATE"
   "<TRIGGER_OPERATING_STATE-REQUEST>"
   "TRIGGER_OPERATING_STATE-REQUEST"
   "<TRIGGER_OPERATING_STATE-RESPONSE>"
   "TRIGGER_OPERATING_STATE-RESPONSE"
  ))

