(cl:in-package cisst_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          PERIODAVG-VAL
          PERIODAVG
          PERIODSTDDEV-VAL
          PERIODSTDDEV
          PERIODMIN-VAL
          PERIODMIN
          PERIODMAX-VAL
          PERIODMAX
          COMPUTETIMEAVG-VAL
          COMPUTETIMEAVG
          COMPUTETIMESTDDEV-VAL
          COMPUTETIMESTDDEV
          COMPUTETIMEMIN-VAL
          COMPUTETIMEMIN
          COMPUTETIMEMAX-VAL
          COMPUTETIMEMAX
          NUMBEROFSAMPLES-VAL
          NUMBEROFSAMPLES
          NUMBEROFOVERRUNS-VAL
          NUMBEROFOVERRUNS
          STATISTICSINTERVAL-VAL
          STATISTICSINTERVAL
          USERDATA-VAL
          USERDATA
))